pub const DEFAULT_TITLE_TEMPLATE: &str = "[{{app}} {{notification}}";

pub const DEFAULT_TEXT_TEMPLATE: &str = "{{notification}}

--
Email generated by {{tagline}}";

pub const DEFAULT_HTML_TEMPLATE: &str = r#"
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<HTML lang="{{lang}}">
<HEAD></HEAD>
<BODY>
  {{notification}}
  <DIV ID="footer">
    <HR />
    <P><SMALL><EM>Email generated by {{tagline}}.</EM></SMALL></P>
  </DIV>
</BODY>
</HTML>"#;

pub const DEFAULT_MAPPING: &str = r#"
{
    "lang": "en"
}
"#;
